### ISSUE TITLE
2D Interpolation

### ISSUE THREAD

**Issue by alhaDHI** [wo80/Triangle.NET#10]
I am generating a mesh from scatter data and then interpolating on to another set of data points.

private float[] GetInterpolatedData(double[] x, double[] y, float[] data, double[,] xy)
{
            var points = new List<Vertex>();
            for (var i = 0; i < data.Length; i++)
            {
                points.Add(new Vertex3(x[i], y[i], (double)data[i]));
            }
            var mesher = new GenericMesher(new Dwyer());
            var mesh = (TriangleNet.Mesh)mesher.Triangulate(points);
            var triangleQuadTree = new TriangleQuadTree(mesh);
            var outData = new float[xy.GetLength(0)];
            for (var i = 0; i < xy.GetLength(0); i++)
            {
                var tri = triangleQuadTree.Query(xy[i, 0], xy[i, 1]);
                if (tri != null)
                {
                    var vert = new Vertex3(xy[i, 0], xy[i, 1], double.NaN);
                    InterpolateAttributes(vert, tri);
                    outData[i] = (float)vert.Z;
                }
                else
                {
                    outData[i] = float.NaN;
                }
            }

            return outData;
}

The x and y coordinates of the mesh will remain constant but "data" will change. Can I change the data in the mesh without re-meshing and re-running TriangleQuadTree?

**Comment by justingruenberg** [comment]
I don't see a Vertex3 class in this project.  Looking at the source for InterpolateAttributes, you probably want to create a Vertex object with one attribute as your data value.

**Comment by dewell81** [comment]
Is there any working example on how to use the interpolation function of the library?

I don't really understand what to do with USE_Z

**Comment by eppz** [comment]
I suggest to look around at the archived original repo at https://archive.codeplex.com/?p=triangle.
You can find **issues** and **discussions** there.

**Comment by wo80** [comment]
Or look at the commit history. You'll find https://github.com/eppz/Triangle.NET/commit/aed9de93e5281caf1f23f1fe156058b930f38e5a
```
Add conditional compilation symbols:
USE_ATTRIBS: use vertex attributes (automatic interpolation)
USE_Z: add z-property to Point class (no interpolation)
```

**Comment by dewell81** [comment]
I have around 500 datasets with 3 coordinates. I used the RandomPoints-generator from the mesh explorer as basis for my own generator. I read in around 500 datasets with x,y, and z values. X and Y values are added to each vertex but now my difficulties in how to use the library start.

I now overloaded the Vertex constructor with (x, y, 0, 1) to add one data attribute and added one line where I add the z-value as this dataattribute.

`Vertex newVertex;
            for (int i = 0; i < numPoints; i++)
            {
                newVertex = new Vertex(xValue, yValue , 0, 1);
                newVertex.Attributes[0] = zValue;
                input.Add(newVertex);
            }`

The generation of the mesh and the Delaunay triangulation works but what do I have to do to interpolate x,y coordinates whose z-value I don't know yet?

**Comment by wo80** [comment]
1. If the triangle is given and you want to interpolate the attribute (e.g. z-value) at a point inside the triangle, use the `InterpolateAttributes` method of the [Interpolation](https://github.com/eppz/Triangle.NET/blob/master/Triangle.NET/Triangle/Tools/Interpolation.cs) class.

2. If a point inside the mesh is given, locate the triangle that contains the point (you can use the [TriangleQuadTree](https://github.com/eppz/Triangle.NET/blob/master/Triangle.NET/Triangle/Tools/TriangleQuadTree.cs)) and then do 1.

**Comment by dewell81** [comment]
Thanks a lot. In my case the point x,y will be given, so I locate the right triangle with the the TriangleQuadTree class. Then I use the Query(double x, double y) to get the right triangle from my triangulation. Then I feed the InterpolateAttributes function from Interpolation.cs with all those values and get the wanted dataattribute (in my case the value z) for the given vertex (=x,y point)

**Comment by wo80** [comment]
Closing this one with #16 

See [Triangle.Examples Example10.cs](https://github.com/wo80/Triangle.NET/blob/fd205fbb9c69d974fd3e52c1c4028ed1fba92d87/src/Triangle.Examples/Examples/Example10.cs) for an example doing interpolation without `USE_Z` or `USE_ATTRIBS`.
