### ISSUE TITLE
Implement in own C# project

### ISSUE THREAD

**Issue by Pixel-95** [wo80/Triangle.NET#11]
Is there any beginner tutorial, how to use this library in my own C# project? #

**Comment by eppz** [comment]
I suggest looking around at the original repo at https://archive.codeplex.com/?p=triangle.
You can find archived **issues** and **discussions** there.

**Comment by wo80** [comment]
Probably a bit too late, but I'm currently adding some content to the wiki. That should help people getting started.

https://github.com/wo80/Triangle.NET/wiki
