### ISSUE TITLE
vertices distance/amount parametrization per border

### ISSUE THREAD

**Issue by darek2000** [wo80/Triangle.NET#12]
Hi, is there any option to configure vertices distance (or amount) per border when defining geometry for meshing? (like it is done in freefem mesher where i.e. square borders can be configure: mesh Th = buildmesh(C01(n) + C02(n) + C03(n) + C04(n)) where n means number of vertices per border)

**Comment by wo80** [comment]
Triangle.NET doesn't support this out of the box, but it shouldn't be hard to implement for yourself. Take a look at the `Rectangle` and `Circle` generator methods in [Triangle.Examples/Generate.cs](https://github.com/wo80/Triangle.NET/blob/master/src/Triangle.Examples/Generate.cs#L32) to get started.
