### ISSUE TITLE
SimpleSmoother crash

### ISSUE THREAD

**Issue by timoria21** [wo80/Triangle.NET#18]
Hello, thanks to anybody working on this interesting project. 

I have an issue I cannot understand. It could be a very trivial problem because I can't find more information on attributes like `markers`.

Here is the geometry, the arrow highlights a duplicated point (not sure if I need to clean it or not):
![image](https://user-images.githubusercontent.com/79898585/154643259-553c9dda-c971-4c82-9dbf-b41410c13f63.png)

Here is the crash when I click the Smooth button: face.Edge = null. https://www.screencast.com/t/Yx3xfeGuSdY

I can donate in advance if you know how to help me. Thank you.

The geometry follows:

91 2 0 0
0 60 10
1 59.8012310146161 13.9827138638327
2 59.2068995139417 17.9258457279759
3 58.2229122314456 21.7902069764362
4 56.8590484748163 25.5373918509878
5 55.1288629348091 29.1301591448527
6 53.0495509726398 32.5328023225449
7 50.6417777247591 35.7115043874616
8 47.9294727234429 38.6346739703887
9 44.9395920743493 41.2732592987212
10 41.7018505546304 43.6010369260309
11 38.2484262941265 45.5948723524587
12 34.6136409746558 47.2349499457682
13 30.8336187257202 48.5049698780005
14 26.9459271066772 49.3923101204883
15 22.989203743457 49.8881518872472
16 19.0027723304771 49.9875672800326
17 15.0262518141006 49.6895682640069
18 11.0991626417474 48.9971164872729
19 7.26053398993263 47.9170938466853
20 3.54851587477554 46.4602340924669
21 -7.105427357601E-15 44.6410161513775
22 -3.34974688939159 42.4775202286343
23 -6.46743350387437 39.9912481187094
24 -9.32207487319305 37.2069095108368
25 -11.8853002889169 34.1521764130191
26 -14.1316352652862 30.8574081351799
27 -16.0387547160968 27.3553495647023
28 -17.5877048314363 23.6808057330268
29 -18.7630914491631 19.8702959076118
30 -19.5532330490051 15.961690647047
31 -19.9502768487569 11.9938354264279
32 -19.9502768487569 8.00616457357211
33 -19.5532330490051 4.03830935295302
34 -18.7630914491631 0.129704092388256
35 -17.5877048314363 -3.68080573302675
36 -16.0387547160968 -7.35534956470232
37 -14.1316352652862 -10.8574081351799
38 -11.8853002889169 -14.1521764130191
39 -9.32207487319306 -17.2069095108368
40 -6.46743350387439 -19.9912481187094
41 -3.34974688939162 -22.4775202286342
42 1.4210854715202E-14 -24.6410161513776
43 3.54851587477554 -26.4602340924669
44 7.2605339899326 -27.9170938466853
45 11.0991626417474 -28.9971164872729
46 15.0262518141006 -29.6895682640069
47 19.0027723304771 -29.9875672800326
48 22.989203743457 -29.8881518872472
49 26.9459271066772 -29.3923101204883
50 30.8336187257202 -28.5049698780005
51 34.6136409746558 -27.2349499457682
52 38.2484262941265 -25.5948723524587
53 41.7018505546304 -23.6010369260309
54 44.9395920743493 -21.2732592987212
55 47.9294727234429 -18.6346739703887
56 50.6417777247591 -15.7115043874616
57 53.0495509726398 -12.5328023225449
58 55.1288629348091 -9.13015914485274
59 56.8590484748163 -5.53739185098779
60 58.2229122314456 -1.79020697643619
61 59.2068995139417 2.07415427202409
62 59.8012310146161 6.01728613616731
63 38 30
64 36.9282032302755 34
65 34 36.9282032302755
66 30 38
67 26 36.9282032302755
68 23.0717967697245 34
69 22 30
70 23.0717967697245 26
71 26 23.0717967697245
72 30 22
73 34 23.0717967697245
74 36.9282032302755 26
75 -7.32050807568877 10
76 -8.90001637429337 6.54135926634843
77 -9.79642883761865 2.8462967654657
78 -9.97734678366016 -0.951638316474849
79 -9.43623136647084 -4.71517871018854
80 -8.19263990709037 -8.30830026003773
81 -6.29151904100672 -11.601138191424
82 -3.80158022964224 -14.4746807621014
83 -0.812816349111948 -16.8250706566236
84 2.56675088679344 -18.5673586603214
85 6.21497511279179 -19.6385739452541
86 10 -20
87 60 10
88 55 10
89 52 13
90 52 16
89 0
0 0 1
1 1 2
2 2 3
3 3 4
4 4 5
5 5 6
6 6 7
7 7 8
8 8 9
9 9 10
10 10 11
11 11 12
12 12 13
13 13 14
14 14 15
15 15 16
16 16 17
17 17 18
18 18 19
19 19 20
20 20 21
21 21 22
22 22 23
23 23 24
24 24 25
25 25 26
26 26 27
27 27 28
28 28 29
29 29 30
30 30 31
31 31 32
32 32 33
33 33 34
34 34 35
35 35 36
36 36 37
37 37 38
38 38 39
39 39 40
40 40 41
41 41 42
42 42 43
43 43 44
44 44 45
45 45 46
46 46 47
47 47 48
48 48 49
49 49 50
50 50 51
51 51 52
52 52 53
53 53 54
54 54 55
55 55 56
56 56 57
57 57 58
58 58 59
59 59 60
60 60 61
61 61 62
62 62 0
63 63 64
64 64 65
65 65 66
66 66 67
67 67 68
68 68 69
69 69 70
70 70 71
71 71 72
72 72 73
73 73 74
74 74 63
75 75 76
76 76 77
77 77 78
78 78 79
79 79 80
80 80 81
81 81 82
82 82 83
83 83 84
84 84 85
85 85 86
86 87 88
87 88 89
88 89 90
0

**Comment by wo80** [comment]
You're welcome!

I think this issue has become a bit convoluted. I'll automatically close it when merging the develop branch.

Feel free to open another one if there are more issues or questions.
