### ISSUE TITLE
Quadratic elements

### ISSUE THREAD

**Issue by FoxySeta** [wo80/Triangle.NET#20]
The original Triangle project supports [quadratic elements](https://www.cs.cmu.edu/~quake/triangle.highorder.html), but it appears this project does not.
Is this feature already scheduled for some future release? Are contributions appreciated on this matter?

**Comment by wo80** [comment]
The old  codeplex wiki had an example, here's a gist: [QuadraticElements.cs](https://gist.github.com/wo80/d531b52108327f710a80d301ea37fdc1)

Please review and let me know, if it works.

**Comment by wo80** [comment]
> Thanks! It works as expected.

Great! The gist will be added to the examples wiki page.

**Comment by FoxySeta** [comment]
Glad to hear it. On my side, the problem was solved, so you may close this issue whenever you feel like it.
