### ISSUE TITLE
concave polygon?

### ISSUE THREAD

**Issue by jardeltecchio** [wo80/Triangle.NET#37]
Hello. Sorry, it's a newbie question.
 Is there a way to triangulate a concave polygon? I tried to do so, but i gues i missed something...
here is my code:

            var pol = new Polygon();
            pol.Points.Add(new Vertex(0, 0));
            pol.Points.Add(new Vertex(0.2f, 0));
            pol.Points.Add(new Vertex(0.2f, -0.2f));
            pol.Points.Add(new Vertex(-0.2f, -0.2f));
            pol.Points.Add(new Vertex(-0.2f, -0.15f));
            pol.Points.Add(new Vertex(0, -0.15f));
            pol.Points.Add(new Vertex(0, 0));

            var options = new ConstraintOptions() { ConformingDelaunay = true};
            var qual = new QualityOptions() { MaximumArea = 0.005};
            mesh = (Mesh)pol.Triangulate(options, qual);
             var smoother = new SimpleSmoother();
             smoother.Smooth(mesh);

thanks in advance

this is my atempt to triangulate the blue polygon
![concave polygon](https://user-images.githubusercontent.com/29777001/234731511-c2161dcf-34b1-4705-9a45-9d7b7754ea2f.JPG)

**Comment by a5rGithub** [comment]
You could take a look at the contour example https://github.com/wo80/Triangle.NET/wiki/Polygon

**Comment by jardeltecchio** [comment]
It worked. I should have created the contour or segments. 
Thank you.
