### ISSUE TITLE
Add vertices inside the polygon

### ISSUE THREAD

**Issue by johnnyontheweb** [wo80/Triangle.NET#38]
How to? AddContour adds the polygon, but how to have the resulting mesh passing by some internal points into the polygon?

**Comment by johnnyontheweb** [comment]
I found it, it's .Add - trivial question

**Comment by mustbau** [comment]
Hi, @johnnyontheweb can you add a line of code for adding the internal points to the polygon. that would be very helpful. 
thanks in advance.
