### ISSUE TITLE
changes from triangle.net on codeplex

### ISSUE THREAD

**Issue by astordahl** [wo80/Triangle.NET#4]
I've been using the triangle.net code that was on codeplex (https://archive.codeplex.com/?p=triangle).  This code seems to be based on that, but has quite a few differences.  When did the basic code setup change?

**Comment by eppz** [comment]
You can lookup commits / branches at https://github.com/eppz/Triangle.NET/commits/master. You can find a point before my patches for Unity (I can't recall the exact commit or branch).

**Comment by wo80** [comment]
I set up a short history wiki page: https://github.com/wo80/Triangle.NET/wiki/History
