### ISSUE TITLE
using the library from IronPyton

### ISSUE THREAD

**Issue by xyont** [wo80/Triangle.NET#41]
hi,

interesting library to use, i'm call and loading from IronPyton but failed at triangulation. Any hints or suggestion?

regards,

![2023-10-27 11_23_42-test40 py - SciTE](https://github.com/wo80/Triangle.NET/assets/72367311/8b9ae0b6-9f50-49ef-85a8-ff892021f86a)

**Comment by wo80** [comment]
The `polygon.Triangulate(...)` methods are extension methods defined in [Triangle/Geometry/ExtensionMethods.cs](https://github.com/wo80/Triangle.NET/blob/master/src/Triangle/Geometry/ExtensionMethods.cs). I've never used IronPython, but you might need to do something like `clr.ImportExtensions(TriangleNet.Geometry)`, see this [stackoverflow question](https://stackoverflow.com/questions/628482/can-you-use-linq-types-and-extension-methods-in-ironpython).

Alternatively, just use the `GenericMesher` class, as done by the extension methods.

**Comment by xyont** [comment]
many thanks for such as guidance, it seems to be working now. Next is related to save mesh results, any example?

![2023-10-27 16_11_47-test40 py - SciTE](https://github.com/wo80/Triangle.NET/assets/72367311/b8f6baa7-8a93-4c40-af37-f5694d0fb2d4)

**Comment by wo80** [comment]
> Next is related to save mesh results, any example?

It depends on what you actually want to do. You can use `FileProcessor.Write(mesh, filename)`, which uses the original [Triangle format](https://www.cs.cmu.edu/~quake/triangle.ele.html). Or access the data of the `IMesh` directly and write in any format you like using Python...

**Comment by xyont** [comment]
firstly, i need to save as default format (mesh file & SVG for viewing) but did not succeed,

add commands,
`SvgImage.Save(mesh, "box.svg", 500)`
shown a message,
`NameError: global name 'SvgImage' is not defined`

add commands,
`FileProcessor.Write(mesh, box)`
shown a message,
`NameError: global name 'FileProcessor' is not defined`

**Comment by wo80** [comment]
> NameError: global name 'SvgImage' is not defined

Have you built and added a reference to the _Triangle.Rendering_ assembly? Imported the `TriangleNet.Rendering.Text` namespace?

**Comment by xyont** [comment]
add command,
`clr.ImportExtensions(TriangleNet.Rendering.Text)
`

shown a message,
`AttributeError: 'TriangleNet' object has no attribute 'Rendering'
`

**Comment by wo80** [comment]
> Have you built and added a reference to the Triangle.Rendering assembly?

You seem to have a `Triangle.dll`, since `clr.AddReference("Triangle.dll")` is working. Now you also need to build the [src/Triangle.Rendering/Triangle.Rendering.csproj](https://github.com/wo80/Triangle.NET/tree/master/src/Triangle.Rendering) project, which will give you a `Triangle.Rendering.dll`. Then
```python
clr.AddReference("Triangle.Rendering.dll")

import TriangleNet.Rendering
from TriangleNet.Rendering import *

Text.SvgImage.Save(mesh, "box.svg", 500)
```
As already mentioned, I don't use IronPython, so I haven't the code above, but that seems to be the way IronPython handles .NET assemblies...

**Comment by xyont** [comment]
hello again, i have some problem in saving *.node file, were previously successful for *.ele files. Request an output of *.node file did not show any error, but the file is not created or available in the directory. 

any suggestion? thank you.
