### ISSUE TITLE
Deep copy a mesh surface

### ISSUE THREAD

**Issue by AllenTaiTW** [wo80/Triangle.NET#45]
How to deep copy a mesh surface because adjustments to the z-coordinate are needed. Currently, I'm reconstructing a new mesh using the point set of the mesh, but if the former has undergone operations such as flipping, the reconstruction won't be optimal.

**Comment by wo80** [comment]
Cloning isn't supported out of the box. You can try the following code, it should be fairly efficient. Let me know if that works. If it doesn't, you're welcome to do a pull request adding the features you need.
```c#
using System.Linq;
using TriangleNet;
using TriangleNet.Geometry;
using TriangleNet.Meshing;
using TriangleNet.Topology;

public static Mesh Clone(IMesh mesh)
{
    mesh.Renumber();

    var p = new Polygon(mesh.Vertices.Count);

    var vertices = mesh.Vertices;

    // Make sure to use the correct type here (point including z-coordinate) and to copy the id.
    p.Points.AddRange(vertices.Select(p => new Vertex(p.X, p.Y, p.Z, p.Label) { ID = p.ID }));
    p.Segments.AddRange(mesh.Segments.Cast<SubSegment>().Select(s => new Segment(s.GetVertex(0), s.GetVertex(1), s.Label)));

    var m = Converter.Instance.ToMesh(p, mesh.Triangles.ToList());

    // Add missing data manually (for example holes, if needed)

    return m;
}
```

**Comment by AllenTaiTW** [comment]
You're welcome! The Clone() method works very well. It would be great if we could also deep copy the mesh.Segments.

**Comment by wo80** [comment]
Ok, I missed that the converter will reference the original vertices of the segments. Please replace
```c#
p.Segments.AddRange(mesh.Segments);
```
with
```c#
// Make sure the segments reference the new points (this works because the mesh vertices are numbered linearly).
p.Segments.AddRange(mesh.Segments.Select(s => new Segment(p.Points[s.P0], p.Points[s.P1], s.Label)));
```
If you think we are done here, please close the issue.
