### ISSUE TITLE
Unable to triangulate concave polygon

### ISSUE THREAD

**Issue by totenk0pf** [wo80/Triangle.NET#47]
Hi, I'm trying to triangulate a polygon based on a set of boundary points, but it's giving me a weird looking mesh. Since the resulting mesh has to be concave, i've added both the vertices and a contour but the result is misshapen. Is there something I'm doing wrong here?
```csharp
var vertices = new List<Vertex>();
var polygon = new Polygon();
foreach (var tile in _edgeTiles)
{
    // Calculate edge point here
    var point = ...
    _edgeVertices.Add(point);
    var vert = new Vertex(point.x, point.z, 1);
    vertices.Add(vert);
}

polygon.Points.AddRange(vertices);
polygon.Add(new Contour(vertices, 1));

// Start triangulation
var options = new ConstraintOptions
{
    ConformingDelaunay = true, Convex = false
};
var mesh = polygon.Triangulate(options);
```
Thanks in advance.

Here's a visualization of the result (the red circles are the calculated boundary points, the yellow lines are edges from the mesh):

![image](https://github.com/wo80/Triangle.NET/assets/50345722/a1c806f2-25be-4869-8bd4-2188ddc15679)

**Comment by wo80** [comment]
Do not add input vertices twice, add the contour only.

The visualization seems to suggest that your input points are not in order, which they have to be when using the `Contour` class. If you have an unordered list of segments only, then use those segments like shown here: [wiki/Polygon#using-segments](https://github.com/wo80/Triangle.NET/wiki/Polygon#using-segments)

I'd also like to refer you to https://github.com/wo80/Triangle.NET/issues/40#issuecomment-1732079366 for troubleshooting.

**Comment by totenk0pf** [comment]
Thank you, it turns out my input points weren't in order like you said. Works perfectly now.
