### ISSUE TITLE
3D polyhedra

### ISSUE THREAD

**Issue by Minami77** [wo80/Triangle.NET#51]
Hi,
I am trying to generate concave 3D polyhedra from a series of point clouds in unity. Does this library only work with 2D data?
Thanks in advance.

**Comment by wo80** [comment]
Yes, Triangle.NET is 2D only.

The only open source point cloud library I know is [PCL](https://pointclouds.org/). It is native C++, but there are C# bindings available at https://github.com/jbruening/PclSharp
